-- ══ THE REVOKE IN 002 AND 003 DID NOTHING ══════════════════════════════════
-- Run this in Supabase → SQL editor, after 003. Safe to run twice.
--
-- 002 and 003 both said:
--
--     revoke update (comp_used, comp_week) on public.profiles from authenticated, anon;
--
-- and both ran without error, and neither had any effect. In Postgres a
-- COLUMN-level revoke cannot take a privilege away from a role that holds the
-- TABLE-level grant — and Supabase grants `authenticated` and `anon` full
-- UPDATE on every table in `public` by default. The revoke succeeded in the
-- sense that nothing was wrong with the statement; it just had nothing to
-- revoke, because the privilege was not held at the column level.
--
-- The result: the weekly comp allowance and the monthly read counter were
-- writable from the browser the entire time. A user could PATCH their own
-- profile and set comp_used back to zero, which is the single thing the meter
-- exists to prevent. It was caught by querying information_schema after the
-- migration rather than trusting "Success. No rows returned" — the migration
-- was fine, the privilege model was not.
--
-- THE FIX, and it is the standard Postgres shape: take the table-level UPDATE
-- away, then grant back exactly the columns the browser is supposed to write.
--
-- The browser writes two: `name` and `market`, from pushProfile() in _auth.js.
-- Nothing else. Everything that decides money or entitlement — plan, trial,
-- comp_used, comp_week, read_used, read_month — becomes unwritable from a
-- browser by PRIVILEGE rather than by policy, which is a stronger guarantee
-- and one that does not depend on anybody keeping a WITH CHECK clause correct.
--
-- SELECT is untouched: a person can still read their own counters, and should.
-- A number you are being held to is a number you get to see.

revoke update on public.profiles from authenticated, anon;
grant  update (name, market) on public.profiles to authenticated;

-- INSERT, DELETE and TRUNCATE are deliberately left alone. There is no policy
-- permitting INSERT or DELETE, so row-level security already refuses both, and
-- the row itself is created by the signup trigger rather than by the browser —
-- revoking INSERT here risks breaking signup to close a door that is already
-- shut. If that changes, this is the file it belongs in.
